### PR TITLE
Allow json shortcut methods

### PR DESCRIPTION
**Pull request by pape-io**
Shortcut should
- Request JSON
- Parse json when `.data` is requested

Solves: https://github.com/local-ch/lhc/issues/15

### CODE REVIEW

**Comment by skaestle** [comment]
:+1: although, I personally would have went for `LHC.get(format: json)` (but I don't know the history of this PR, so...)

**Comment by acoiro** [comment]
:+1:

**Comment by pape-io** [comment]
@skaestle: The reason to go this way is to keep the method name and the signature clean, consistent and comprehensible.

```ruby
LHC.get('local.ch', params: { limit: 1 })
LHC.json.get('local.ch', params: { limit: 1 })
```

**Comment by skaestle** [comment]
sounds reasonable :+1:

**Pull request merged**
