### PR TITLE
+ encode url and url params in order to not violate HTTP

### PR DESCRIPTION
**Pull request by pape-io**
fixes https://github.com/local-ch/lhc/issues/30

### Major version ahead

### CODE REVIEW

**Comment by pape-io** [comment]
jenkins: test

**Comment by pape-io** [comment]
jenkins: test

**Comment by Averethel** [comment]
LGTM, but please squash merge it ;)

**Comment by pape-io** [comment]
I'll do @Averethel

**Comment by pape-io** [comment]
Squashed merged on master

**Comment by Averethel** [comment]
:+1:

**Pull request closed without merging**
